In [39]:
regioni = ["lazio", "abruzzo", "marche"]

In [40]:
", ".join(regioni).title()

'Lazio, Abruzzo, Marche'

In [41]:
", ".join([r[0].upper()+"." for r in regioni])

'L., A., M.'

In [ ]:
# 1 una lista di liste potrebbe rappesentare i valori di una tabella.
# per accedere a un elemento in particolare vanno messe le prime parentesi quadre per indicare la lista,
# le seconde parentesi quadre per il valore in quella lista 

In [1]:
mat = [[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14]]

In [42]:
mat[0]

array([0, 1, 2, 3, 4])

In [6]:
len(mat) 

3

In [7]:
mat[1][3]

8

In [ ]:
# 2 

In [9]:
import numpy as np

In [10]:
mat = np.array(mat)

In [11]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
mat[1][3]

8

In [43]:
mat[1, 3]

8

In [15]:
# 3

In [16]:
linear_data = np.array([x for x in range(27)])

In [17]:
linear_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [18]:
reshape_data = linear_data.reshape((3, 3, 3))

In [19]:
reshape_data

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [20]:
len(reshape_data)

3

In [21]:
reshape_data[1][1][0]

12

In [44]:
reshape_data[1, 1, 0]

12

In [ ]:
# 4

In [45]:
aree = np.zeros([2, 2])
aree

array([[0., 0.],
       [0., 0.]])

In [46]:
for count in range(100):
    r = np.random.randint(0, 2)
    c = np.random.randint(0, 2)
    #rc = np.random.randint(0, 2, [2])
    aree[r, c] += 1

In [47]:
aree

array([[23., 23.],
       [24., 30.]])

In [48]:
aree[0, 1]

23.0

In [49]:
aree[1, 0]

24.0

In [50]:
aree > 25

array([[False, False],
       [False,  True]])

In [51]:
aree = np.zeros([2, 2])
for count in range(100):
    r = np.random.randint(0, 2)
    c = np.random.randint(0, 2)
    #rc = np.random.randint(0, 2, [2])
    aree[r, c] += 1

In [52]:
aree

array([[23., 27.],
       [29., 21.]])

In [53]:
filtro = aree > 25

In [55]:
store25 = aree[filtro]

In [56]:
store25

array([27., 29.])

In [58]:
store25.sum()

56.0

In [ ]:
# 5

In [59]:
aree = np.zeros((3, 3))
for count in range(200):
    r = np.random.randint(0, 3)
    c = np.random.randint(0, 3)
    aree[r, c] += 1

In [60]:
aree

array([[27., 18., 16.],
       [26., 31., 19.],
       [21., 22., 20.]])

In [61]:
filtro = aree > 25

In [62]:
filtro

array([[ True, False, False],
       [ True,  True, False],
       [False, False, False]])

In [ ]:
# 6

In [28]:
while True:
    try:
        x = int(input("introduci un numero: "))
        risultato = x/5
        print("il risultato del numero inserito diviso 5 è:", risultato)
        break
    except ValueError:
        print("Oops! il valore inserito non era valido. ritenta!")

introduci un numero:  a


Oops! il valore inserito non era valido. ritenta!


introduci un numero:  5


il risultato del numero inserito diviso 5 è: 1.0


In [ ]:
# 7

In [ ]:
# 8

In [1]:
import pandas as pd

In [4]:
iris = pd.read_csv("iris.data", names=["sepal length in cm", "sepal width in cm", 
                   "petal length in cm", "petal width in cm", "class"])

In [5]:
pd.DataFrame(iris)

sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm           class  
0                  0.2     Iris-setosa  
1                  0.2     Iris-setosa  
2                  0.2     Iris-setosa  
3                  0.2     Iris-setosa  
4                  0.2     Iris-setosa  
..                 ...             ...  
145                2.3  Iris-virginica  
146                1.9  Iris-virginica  
147                2.0  Iris-virginica  
148                2.3  Iris-virginica  
149                1.8  Iris-virginica  

[150 rows x 5 columns]

In [3]:
pd.DataFrame(iris,
             index=range(1,150,1),
             columns=["sepal length in cm", "sepal width in cm", 
                   "petal length in cm", "petal width in cm", "class"])

sepal length in cm  sepal width in cm  petal length in cm  \
1                   NaN                NaN                 NaN   
2                   NaN                NaN                 NaN   
3                   NaN                NaN                 NaN   
4                   NaN                NaN                 NaN   
5                   NaN                NaN                 NaN   
..                  ...                ...                 ...   
145                 NaN                NaN                 NaN   
146                 NaN                NaN                 NaN   
147                 NaN                NaN                 NaN   
148                 NaN                NaN                 NaN   
149                 NaN                NaN                 NaN   

     petal width in cm  class  
1                  NaN    NaN  
2                  NaN    NaN  
3                  NaN    NaN  
4                  NaN    NaN  
5                  NaN    NaN  
..                 ...    ...  
145                NaN    NaN  
146                NaN    NaN  
147                NaN    NaN  
148                NaN    NaN  
149                NaN    NaN  

[149 rows x 5 columns]

In [17]:
dim = iris.shape 
print(dim)

(149, 5)


In [5]:
print(dim[0])

149


In [6]:
print(dim[1])

5


In [18]:
print(iris)

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [6]:
iris.head(5)

sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa

In [12]:
iris.tail(10)

sepal length in cm  sepal width in cm  petal length in cm  \
140                 6.7                3.1                 5.6   
141                 6.9                3.1                 5.1   
142                 5.8                2.7                 5.1   
143                 6.8                3.2                 5.9   
144                 6.7                3.3                 5.7   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm           class  
140                2.4  Iris-virginica  
141                2.3  Iris-virginica  
142                1.9  Iris-virginica  
143                2.3  Iris-virginica  
144                2.5  Iris-virginica  
145                2.3  Iris-virginica  
146                1.9  Iris-virginica  
147                2.0  Iris-virginica  
148                2.3  Iris-virginica  
149                1.8  Iris-virginica

In [8]:
iris.columns

Index(['sepal length in cm', 'sepal width in cm', 'petal length in cm',
       'petal width in cm', 'class'],
      dtype='object')

In [9]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [10]:
import numpy as np

In [11]:
iris.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [17]:
round(iris.describe(),1)

sepal length in cm  sepal width in cm  petal length in cm  \
count               150.0              150.0               150.0   
mean                  5.8                3.1                 3.8   
std                   0.8                0.4                 1.8   
min                   4.3                2.0                 1.0   
25%                   5.1                2.8                 1.6   
50%                   5.8                3.0                 4.4   
75%                   6.4                3.3                 5.1   
max                   7.9                4.4                 6.9   

       petal width in cm  
count              150.0  
mean                 1.2  
std                  0.8  
min                  0.1  
25%                  0.3  
50%                  1.3  
75%                  1.8  
max                  2.5

In [ ]:
# 9

In [15]:
wine_dataset = pd.read_csv("wine.csv")

In [16]:
pd.DataFrame(wine_dataset)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality   type  
0         9.4        5    red  
1         9.8        5    red  
2         9.8        5    red  
3         9.8        6    red  
4         9.4        5    red  
...       ...      ...    ...  
6492     11.2        6  white  
6493      9.6        5  white  
6494      9.4        6  white  
6495     12.8        7  white  
6496     11.8        6  white  

[6497 rows x 13 columns]

In [17]:
wine_dataset.head(20)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4             0.700         0.00             1.9      0.076   
1             7.8             0.880         0.00             2.6      0.098   
2             7.8             0.760         0.04             2.3      0.092   
3            11.2             0.280         0.56             1.9      0.075   
4             7.4             0.700         0.00             1.9      0.076   
5             7.4             0.660         0.00             1.8      0.075   
6             7.9             0.600         0.06             1.6      0.069   
7             7.3             0.650         0.00             1.2      0.065   
8             7.8             0.580         0.02             2.0      0.073   
9             7.5             0.500         0.36             6.1      0.071   
10            6.7             0.580         0.08             1.8      0.097   
11            7.5             0.500         0.36             6.1      0.071   
12            5.6             0.615         0.00             1.6      0.089   
13            7.8             0.610         0.29             1.6      0.114   
14            8.9             0.620         0.18             3.8      0.176   
15            8.9             0.620         0.19             3.9      0.170   
16            8.5             0.280         0.56             1.8      0.092   
17            8.1             0.560         0.28             1.7      0.368   
18            7.4             0.590         0.08             4.4      0.086   
19            7.9             0.320         0.51             1.8      0.341   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56   
1                  25.0                  67.0   0.9968  3.20       0.68   
2                  15.0                  54.0   0.9970  3.26       0.65   
3                  17.0                  60.0   0.9980  3.16       0.58   
4                  11.0                  34.0   0.9978  3.51       0.56   
5                  13.0                  40.0   0.9978  3.51       0.56   
6                  15.0                  59.0   0.9964  3.30       0.46   
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
9                  17.0                 102.0   0.9978  3.35       0.80   
10                 15.0                  65.0   0.9959  3.28       0.54   
11                 17.0                 102.0   0.9978  3.35       0.80   
12                 16.0                  59.0   0.9943  3.58       0.52   
13                  9.0                  29.0   0.9974  3.26       1.56   
14                 52.0                 145.0   0.9986  3.16       0.88   
15                 51.0                 148.0   0.9986  3.17       0.93   
16                 35.0                 103.0   0.9969  3.30       0.75   
17                 16.0                  56.0   0.9968  3.11       1.28   
18                  6.0                  29.0   0.9974  3.38       0.50   
19                 17.0                  56.0   0.9969  3.04       1.08   

    alcohol  quality type  
0       9.4        5  red  
1       9.8        5  red  
2       9.8        5  red  
3       9.8        6  red  
4       9.4        5  red  
5       9.4        5  red  
6       9.4        5  red  
7      10.0        7  red  
8       9.5        7  red  
9      10.5        5  red  
10      9.2        5  red  
11     10.5        5  red  
12      9.9        5  red  
13      9.1        5  red  
14      9.2        5  red  
15      9.2        5  red  
16     10.5        7  red  
17      9.3        5  red  
18      9.0        4  red  
19      9.2        6  red

In [22]:
wine_dataset.tail(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
6492            6.2              0.21         0.29             1.6      0.039   
6493            6.6              0.32         0.36             8.0      0.047   
6494            6.5              0.24         0.19             1.2      0.041   
6495            5.5              0.29         0.30             1.1      0.022   
6496            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
6492                 24.0                  92.0  0.99114  3.27       0.50   
6493                 57.0                 168.0  0.99490  3.15       0.46   
6494                 30.0                 111.0  0.99254  2.99       0.46   
6495                 20.0                 110.0  0.98869  3.34       0.38   
6496                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality   type  
6492     11.2        6  white  
6493      9.6        5  white  
6494      9.4        6  white  
6495     12.8        7  white  
6496     11.8        6  white

In [10]:
wine_dataset_lastsixcolumns = pd.read_csv("wine.csv", usecols=[7, 8, 9, 10, 11, 12])

In [11]:
wine_dataset_lastsixcolumns

density    pH  sulphates  alcohol  quality   type
0     0.99780  3.51       0.56      9.4        5    red
1     0.99680  3.20       0.68      9.8        5    red
2     0.99700  3.26       0.65      9.8        5    red
3     0.99800  3.16       0.58      9.8        6    red
4     0.99780  3.51       0.56      9.4        5    red
...       ...   ...        ...      ...      ...    ...
6492  0.99114  3.27       0.50     11.2        6  white
6493  0.99490  3.15       0.46      9.6        5  white
6494  0.99254  2.99       0.46      9.4        6  white
6495  0.98869  3.34       0.38     12.8        7  white
6496  0.98941  3.26       0.32     11.8        6  white

[6497 rows x 6 columns]

In [19]:
round(wine_dataset_lastsixcolumns.describe(), 2)

density       pH  sulphates  alcohol  quality
count  6497.00  6497.00    6497.00  6497.00  6497.00
mean      0.99     3.22       0.53    10.49     5.82
std       0.00     0.16       0.15     1.19     0.87
min       0.99     2.72       0.22     8.00     3.00
25%       0.99     3.11       0.43     9.50     5.00
50%       0.99     3.21       0.51    10.30     6.00
75%       1.00     3.32       0.60    11.30     6.00
max       1.04     4.01       2.00    14.90     9.00

In [ ]:
# 10

In [30]:
fatturati_dict ={1997: 12_000, 1998: 15_000, 
                1999: 20_000, 2000: 23_000,
                2001: 25_000, 2002: 17_000, 
                 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
                             index=range(1997, 2005))

In [27]:
print(fatturati_series)

1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64


In [28]:
print(fatturati_dict)

{1997: 12000, 1998: 15000, 1999: 20000, 2000: 23000, 2001: 25000, 2002: 17000, 2003: 14000, 2004: 21000}


In [25]:
fatturati_dict[1997]

12000

In [31]:
fatturati_series[1997]

12000

In [34]:
fatturati_series.loc["1999":"2003"]

1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
dtype: int64

In [36]:
fatturati_series.iloc[2:-1]

1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
dtype: int64

In [38]:
fatturati_dict["1997":"2002"]

TypeError: unhashable type: 'slice'

In [39]:
# si può stampare solo un elemento del dizionario, invece con la series si possono fare raggrappamenti

